<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RxFlow.Application\RxFlow.Application.csproj" />
    <ProjectReference Include="..\RxFlow.Contracts\RxFlow.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" />
  </ItemGroup>
</Project>